import "@/styles/global.css";
import "@/styles/reset.css";

export const metadata = {
  title: "Netfilms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">{children}</body>
    </html>
  );
}
